# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Coverity Tools Download
        run: |
            set -x
            
            curl -kfLsS --user ${{secrets.REPO_USER}}:${{secrets.REPO_PASS}} -o sigma ${{secrets.REPO_URL}}/downloadFile.htm?fn=sigma
            chmod 777 sigma
            mv sigma $GITHUB_WORKSPACE/
            
            $GITHUB_WORKSPACE/sigma analyze --format SARIF
            
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: sigma-results.json
